# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0002_auto_20190314_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
